/* ============================================================
   FILE: app/adminpage/AdminListings/styles.ts   (NEW)
   Shared inline styles for the Listings admin (mirrors AdminDashboard.tsx).
   ============================================================ */

import type { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  body: { fontFamily: "'Segoe UI', sans-serif", background: "#f0f4f8", display: "flex", minHeight: "100vh" },
  sidebar: {
    width: 240,
    background: "#1a5c38",
    color: "#fff",
    display: "flex",
    flexDirection: "column",
    minHeight: "100vh",
    position: "fixed",
    top: 0,
    left: 0,
    zIndex: 50,
  },
  logoBlock: { padding: "24px 24px 18px", borderBottom: "1px solid rgba(255,255,255,.15)" },
  logoH2: { fontSize: "1.2rem", fontWeight: 700 },
  logoP: { fontSize: ".75rem", opacity: 0.65, marginTop: 2 },
  adminBadge: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "14px 24px",
    borderBottom: "1px solid rgba(255,255,255,.1)",
    background: "rgba(0,0,0,.12)",
  },
  adminAvatar: {
    width: 34,
    height: 34,
    background: "rgba(255,255,255,.25)",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: ".9rem",
    fontWeight: 700,
    flexShrink: 0,
  },
  adminName: { fontSize: ".82rem", fontWeight: 600, color: "#fff" },
  adminRole: { fontSize: ".7rem", color: "rgba(255,255,255,.6)", textTransform: "capitalize" },
  menu: { listStyle: "none", padding: "16px 0", flex: 1 },
  menuLink: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "12px 24px",
    color: "rgba(255,255,255,.82)",
    textDecoration: "none",
    fontSize: ".88rem",
  },
  menuLinkActive: { background: "rgba(255,255,255,.15)", color: "#fff" },
  menuIcon: { width: 16, textAlign: "center" },
  content: { marginLeft: 240, padding: "32px 36px", flex: 1 },
  header: { display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 6 },
  headerH1: { fontSize: "1.4rem", color: "#1a3d28", fontWeight: 700 },
  subtitle: { fontSize: ".85rem", color: "#778", marginBottom: 28 },
  stats: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))",
    gap: 18,
    marginBottom: 24,
  },
  statCard: {
    background: "#fff",
    borderRadius: 12,
    padding: "20px 18px",
    textAlign: "center",
    boxShadow: "0 2px 10px rgba(0,0,0,.07)",
  },
  statIcon: { fontSize: "1.5rem", color: "#1a5c38", marginBottom: 6, display: "block" },
  statH2: { fontSize: "1.7rem", fontWeight: 700, color: "#1a3d28" },
  statP: { fontSize: ".78rem", color: "#777", marginTop: 2 },
  filterRow: { display: "flex", gap: 10, marginBottom: 22, flexWrap: "wrap" },
  filterChip: {
    padding: "8px 18px",
    borderRadius: 20,
    borderWidth: 1.5,
    borderStyle: "solid",
    borderColor: "#d8e2da",
    background: "#fff",
    color: "#556",
    fontSize: ".82rem",
    fontWeight: 600,
    cursor: "pointer",
  },
  filterChipActive: { background: "#1a5c38", borderColor: "#1a5c38", color: "#fff" },
  panelState: {
    textAlign: "center",
    padding: "50px 10px",
    color: "#888",
    fontSize: ".9rem",
    background: "#fff",
    borderRadius: 12,
    boxShadow: "0 2px 10px rgba(0,0,0,.07)",
  },
  bizGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(320px, 1fr))", gap: 20 },
  bizCard: { background: "#fff", borderRadius: 12, padding: 20, boxShadow: "0 2px 10px rgba(0,0,0,.07)" },
  bizCardHead: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 10, marginBottom: 12 },
  bizName: { fontSize: "1rem", fontWeight: 700, color: "#1a3d28" },
  bizMeta: { fontSize: ".78rem", color: "#889", marginTop: 3 },
  tag: { padding: "4px 12px", borderRadius: 20, fontSize: ".72rem", fontWeight: 700, textTransform: "capitalize", flexShrink: 0 },
  thumbRow: { display: "flex", gap: 8, marginBottom: 12, overflowX: "auto" },
  thumb: { width: 64, height: 64, objectFit: "cover", borderRadius: 8, cursor: "pointer", flexShrink: 0, background: "#e8f0ec" },
  docList: { display: "flex", flexDirection: "column", gap: 6, marginBottom: 12 },
  docLink: { fontSize: ".8rem", color: "#1a5c38", textDecoration: "none", display: "flex", alignItems: "center", gap: 6 },
  rejectionNote: {
    fontSize: ".8rem",
    color: "#c0392b",
    background: "#fdecea",
    borderRadius: 8,
    padding: "8px 12px",
    marginBottom: 8,
  },
  requestNote: {
    fontSize: ".8rem",
    color: "#1a5c38",
    background: "#eef6f0",
    borderRadius: 8,
    padding: "8px 12px",
    marginBottom: 8,
  },
  liveBadge: { fontSize: ".78rem", color: "#155724", background: "#d4edda", borderRadius: 8, padding: "6px 10px", marginBottom: 8 },
  hiddenBadge: { fontSize: ".78rem", color: "#556", background: "#eef1ef", borderRadius: 8, padding: "6px 10px", marginBottom: 8 },
  bizActions: { display: "flex", gap: 10, marginTop: 8 },
  approveBtn: {
    flex: 1,
    background: "#1a5c38",
    color: "#fff",
    border: "none",
    padding: "9px 12px",
    borderRadius: 8,
    fontSize: ".82rem",
    fontWeight: 600,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  approveBtnSolid: {
    padding: "9px 22px",
    borderRadius: 8,
    fontSize: ".88rem",
    fontWeight: 600,
    cursor: "pointer",
    border: "none",
    background: "#1a5c38",
    color: "#fff",
  },
  rejectBtn: {
    flex: 1,
    background: "#fff",
    color: "#c0392b",
    border: "1.5px solid #c0392b",
    padding: "9px 12px",
    borderRadius: 8,
    fontSize: ".82rem",
    fontWeight: 600,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  modalOverlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,.45)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 8000,
  },
  modalBox: {
    background: "#fff",
    borderRadius: 14,
    padding: "30px 32px",
    maxWidth: 380,
    width: "90%",
    textAlign: "center",
    boxShadow: "0 8px 32px rgba(0,0,0,.18)",
  },
  modalTitle: { fontSize: "1.1rem", fontWeight: 700, color: "#1a3d28", marginBottom: 8 },
  modalText: { fontSize: ".85rem", color: "#666", marginBottom: 14 },
  modalTextarea: {
    width: "100%",
    minHeight: 80,
    border: "1px solid #d8e2da",
    borderRadius: 8,
    padding: 10,
    fontSize: ".85rem",
    resize: "vertical",
    fontFamily: "inherit",
  },
  fLabel: { display: "block", fontSize: ".75rem", fontWeight: 600, color: "#556", margin: "12px 0 4px" },
  fInput: {
    width: "100%",
    border: "1px solid #d8e2da",
    borderRadius: 8,
    padding: "9px 10px",
    fontSize: ".85rem",
    fontFamily: "inherit",
  },
  modalCancelBtn: {
    padding: "9px 24px",
    borderRadius: 8,
    fontSize: ".88rem",
    fontWeight: 600,
    cursor: "pointer",
    border: "none",
    background: "#e8f0ec",
    color: "#333",
  },
  modalRejectBtn: {
    padding: "9px 24px",
    borderRadius: 8,
    fontSize: ".88rem",
    fontWeight: 600,
    cursor: "pointer",
    border: "none",
    background: "#c0392b",
    color: "#fff",
  },
  imageModalOverlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,.85)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 9000,
    cursor: "zoom-out",
  },
  imageModalImg: { maxWidth: "90vw", maxHeight: "85vh", borderRadius: 10 },

  /* ── Explore manager (added) ── */
  tabRow: { display: "flex", gap: 6, marginBottom: 22, borderBottom: "2px solid #dfe8e2" },
  tabBtn: {
    padding: "10px 20px",
    background: "transparent",
    border: "none",
    borderBottom: "3px solid transparent",
    marginBottom: -2,
    fontSize: ".9rem",
    fontWeight: 700,
    color: "#778",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  tabBtnActive: { color: "#1a5c38", borderBottomColor: "#1a5c38" },
  tabCount: {
    background: "#1a5c38",
    color: "#fff",
    borderRadius: 20,
    fontSize: ".7rem",
    padding: "1px 8px",
    fontWeight: 700,
  },
  exploreBar: { display: "flex", gap: 10, flexWrap: "wrap", alignItems: "center", marginBottom: 14 },
  searchInput: {
    flex: 1,
    minWidth: 200,
    border: "1px solid #d8e2da",
    borderRadius: 8,
    padding: "9px 12px",
    fontSize: ".85rem",
    fontFamily: "inherit",
    background: "#fff",
  },
  selectInput: {
    border: "1px solid #d8e2da",
    borderRadius: 8,
    padding: "9px 10px",
    fontSize: ".85rem",
    fontFamily: "inherit",
    background: "#fff",
  },
  importBanner: {
    background: "#fff8e1",
    border: "1px solid #f3dc8a",
    color: "#7a5b00",
    borderRadius: 10,
    padding: "14px 16px",
    marginBottom: 16,
    display: "flex",
    gap: 14,
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    fontSize: ".85rem",
    lineHeight: 1.45,
  },
  noticeOk: {
    background: "#d4edda",
    color: "#155724",
    borderRadius: 8,
    padding: "9px 14px",
    marginBottom: 14,
    fontSize: ".83rem",
  },
  noticeErr: {
    background: "#fdecea",
    color: "#c0392b",
    borderRadius: 8,
    padding: "9px 14px",
    marginBottom: 14,
    fontSize: ".83rem",
  },
  tableWrap: {
    background: "#fff",
    borderRadius: 12,
    boxShadow: "0 2px 10px rgba(0,0,0,.07)",
    overflowX: "auto",
  },
  table: { width: "100%", borderCollapse: "collapse", fontSize: ".84rem" },
  th: {
    textAlign: "left",
    padding: "12px 14px",
    fontSize: ".72rem",
    textTransform: "uppercase",
    letterSpacing: ".04em",
    color: "#778",
    borderBottom: "1px solid #e6ece8",
    whiteSpace: "nowrap",
  },
  td: { padding: "10px 14px", borderBottom: "1px solid #f0f3f1", verticalAlign: "middle" },
  rowThumb: { width: 46, height: 46, objectFit: "cover", borderRadius: 8, background: "#e8f0ec", display: "block" },
  rowThumbEmpty: {
    width: 46,
    height: 46,
    borderRadius: 8,
    background: "#e8f0ec",
    color: "#9ab",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "1.1rem",
  },
  rowName: { fontWeight: 700, color: "#1a3d28" },
  rowSub: { fontSize: ".75rem", color: "#889", marginTop: 2 },
  pillLive: { background: "#d4edda", color: "#155724", borderRadius: 20, padding: "3px 10px", fontSize: ".72rem", fontWeight: 700, whiteSpace: "nowrap" },
  pillHidden: { background: "#eef1ef", color: "#667", borderRadius: 20, padding: "3px 10px", fontSize: ".72rem", fontWeight: 700, whiteSpace: "nowrap" },
  srcBadge: { background: "#eef6f0", color: "#1a5c38", borderRadius: 6, padding: "2px 8px", fontSize: ".7rem", fontWeight: 600, whiteSpace: "nowrap" },
  rowActions: { display: "flex", gap: 6, justifyContent: "flex-end", whiteSpace: "nowrap" },
  smallBtn: {
    background: "#fff",
    color: "#1a5c38",
    border: "1.5px solid #1a5c38",
    padding: "5px 11px",
    borderRadius: 7,
    fontSize: ".76rem",
    fontWeight: 600,
    cursor: "pointer",
  },
  smallBtnDanger: {
    background: "#fff",
    color: "#c0392b",
    border: "1.5px solid #c0392b",
    padding: "5px 11px",
    borderRadius: 7,
    fontSize: ".76rem",
    fontWeight: 600,
    cursor: "pointer",
  },
  photoPreview: { width: 96, height: 96, objectFit: "cover", borderRadius: 10, background: "#e8f0ec", flexShrink: 0 },
  hintText: { fontSize: ".74rem", color: "#889", marginTop: 4, lineHeight: 1.4 },
};